- id: conda-env-store
  name: conda-env-store
  language: conda
  pass_filenames: false
  stages:
    - commit
  entry: conda_env_store
  always_run: true
- id: conda-env-update
  name: conda-env-update
  language: conda
  pass_filenames: false
  stages:
    - merge-commit
  entry: conda_env_update
  always_run: true
